### ISSUE TITLE
PKIX failure on job processing on `make docker push`

### ISSUE THREAD

**Issue by bentito** [operator-framework/java-operator-plugins#23]
#### What did you do?

Ran `make docker-build docker-push IMG=default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1`

#### What did you expect to see?

Error free docker build and push.

#### What did you see instead? Under which circumstances?

```console
memcached-quarkus-operator  $ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: ^C%
memcached-quarkus-operator  $ docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /Users/btofel/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
memcached-quarkus-operator  $ oc project default
Now using project "default" on server "https://api.crc.testing:6443".
memcached-quarkus-operator  $ make docker-build docker-push IMG=default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1
mvn package -Dquarkus.container-image.build=true -Dquarkus.container-image.image=default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.example:memcached-quarkus-operator >---------------
[INFO] Building memcached-quarkus-operator 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ memcached-quarkus-operator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ memcached-quarkus-operator ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ memcached-quarkus-operator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/btofel/workspace/memcached-quarkus-operator/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ memcached-quarkus-operator ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ memcached-quarkus-operator ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ memcached-quarkus-operator ---
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.2.Final:build (default) @ memcached-quarkus-operator ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
Generating 'memcacheds.cache.example.com' version 'v1' with com.example.Memcached (spec: com.example.MemcachedSpec / status: com.example.MemcachedStatus)
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Registered 'com.example.MemcachedSpec' for reflection
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Registered 'com.example.MemcachedStatus' for reflection
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Processed 'com.example.MemcachedController' controller named 'memcachedcontroller' for 'memcacheds.cache.example.com' CR (version 'cache.example.com/v1')
Created file:/Users/btofel/workspace/memcached-quarkus-operator/target/kubernetes/memcacheds.cache.example.com-v1beta1.yml
Created file:/Users/btofel/workspace/memcached-quarkus-operator/target/kubernetes/memcacheds.cache.example.com-v1.yml
[INFO] Checking for existing resources in: /Users/btofel/workspace/memcached-quarkus-operator/src/main/kubernetes.
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for fabric8/java-alpine-openjdk11-jre...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:b459cc59d6c7ddc9fd52f981fc4c187f44a401f2433a1b4110810d2dd9e98a07
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -jar, quarkus-run.jar]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Created container image default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1 (sha256:3fd957ec44ff4b006547f1eb6b4ef51780cb2efb7090478a61b74c5e8a2957b4)

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 8839ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.601 s
[INFO] Finished at: 2021-06-29T14:42:54-04:00
[INFO] ------------------------------------------------------------------------
mvn package -Dquarkus.container-image.push=true -Dquarkus.container-image.image=default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.example:memcached-quarkus-operator >---------------
[INFO] Building memcached-quarkus-operator 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ memcached-quarkus-operator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ memcached-quarkus-operator ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ memcached-quarkus-operator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/btofel/workspace/memcached-quarkus-operator/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ memcached-quarkus-operator ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ memcached-quarkus-operator ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ memcached-quarkus-operator ---
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.2.Final:build (default) @ memcached-quarkus-operator ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
Generating 'memcacheds.cache.example.com' version 'v1' with com.example.Memcached (spec: com.example.MemcachedSpec / status: com.example.MemcachedStatus)
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Registered 'com.example.MemcachedSpec' for reflection
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Registered 'com.example.MemcachedStatus' for reflection
[INFO] [io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor] Processed 'com.example.MemcachedController' controller named 'memcachedcontroller' for 'memcacheds.cache.example.com' CR (version 'cache.example.com/v1')
Created file:/Users/btofel/workspace/memcached-quarkus-operator/target/kubernetes/memcacheds.cache.example.com-v1beta1.yml
Created file:/Users/btofel/workspace/memcached-quarkus-operator/target/kubernetes/memcacheds.cache.example.com-v1.yml
[INFO] Checking for existing resources in: /Users/btofel/workspace/memcached-quarkus-operator/src/main/kubernetes.
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] No container image registry was set, so 'docker.io' will be used
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=Docker config auths section defines credentials for default-route-openshift-image-registry.apps-crc.testing]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=LIFECYCLE, message=Using credentials from Docker config (/Users/btofel/.docker/config.json) for default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator:0.0.1]
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor] I/O error for image [default-route-openshift-image-registry.apps-crc.testing/default/memcached-quarkus-operator-operator]:
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor]     javax.net.ssl.SSLHandshakeException
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor]     PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for fabric8/java-alpine-openjdk11-jre...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:b459cc59d6c7ddc9fd52f981fc4c187f44a401f2433a1b4110810d2dd9e98a07
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.329 s
[INFO] Finished at: 2021-06-29T14:43:03-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.12.2.Final:build (default) on project memcached-quarkus-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:191)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:137)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: com.google.cloud.tools.jib.api.InsecureRegistryException: Failed to verify the server at https://default-route-openshift-image-registry.apps-crc.testing/v2/ because only secure connections are allowed.
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:180)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:115)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:624)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:320)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doPushBearerAuth(RegistryClient.java:310)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:65)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:35)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
[ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
[ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
[ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
[ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
[ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
[ERROR] 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
[ERROR] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
[ERROR] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
[ERROR] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
[ERROR] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
[ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1409)
[ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1315)
[ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
[ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
[ERROR] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
[ERROR] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
[ERROR] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
[ERROR] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
[ERROR] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
[ERROR] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
[ERROR] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[ERROR] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[ERROR] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
[ERROR] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
[ERROR] 	at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73)
[ERROR] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:323)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:250)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
[ERROR] 	... 12 more
[ERROR] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[ERROR] 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
[ERROR] 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[ERROR] 	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
[ERROR] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
[ERROR] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
[ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340)
[ERROR] 	... 39 more
[ERROR] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[ERROR] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[ERROR] 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[ERROR] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[ERROR] 	... 45 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
make: *** [docker-push] Error 1
```

#### Environment

**Operator type:**

/language java

**Kubernetes cluster type:**

CRC

`$ operator-sdk version`

```console
$ operator-sdk version
operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "v1.20.2", go version: "go1.16.5", GOOS: "darwin", GOARCH: "amd64"
```

`$ java -version` (if language is Java)

```console
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```
`$ kubectl version`

```console
$ oc version
Client Version: 4.6.16
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
```

#### Possible Solution

`docker login` && `docker push $IMG` worked as workaround.

**Comment by jmrodri** [comment]
You may need to add some options to the pom.xml file or to the make command in the Makefile. Looks like you might be hitting an insecure registry OR it requires authentication.
https://github.com/GoogleContainerTools/jib/issues/2074#issuecomment-579921534

Try adding the following option to the `docker-push` target:

```makefile
docker-push: ## Push docker image with the manager.
    mvn package -Dquarkus.container-image.push=true -Dquarkus.container-image.image=${IMG} -Djib.allowInsecureRegistries=true
```

**Comment by bentito** [comment]
@jmrodri Found it still fails even with that flag.

also I noticed that this fails in exact same way:

```bash
wget https://confluence.atlassian.com/kb/files/779355358/779355357/1/1441897666313/SSLPoke.class
java SSLPoke default-route-openshift-image-registry.apps-crc.testing 443
```

**Comment by bentito** [comment]
Has been tried/failed with other cluster types than CRC too

**Comment by bentito** [comment]
Suggestion from @metacosm that the related quarkus flag to fix this could be `quarkus.container-image.insecure`

**Comment by laxmikantbpandhare** [comment]
@bentito I set the above flag and still facing the same issue.

**Comment by laxmikantbpandhare** [comment]
@jmrodri @metacosm @bentito - I tried below scenarios.

1. Memcached Operator is working on `kind` cluster.
2. It is not working with `minikube` cluster and I tried same scenario after deleting `.kube/config` file as well.

I will create the issue on java-operator-sdk as per discussion on community meeting.

**Comment by metacosm** [comment]
Is this still occurring?

**Comment by bentito** [comment]
I don't have a quick setup to check. Probably best if @laxmikantbpandhare says if he has been able to reproduce?

**Comment by metacosm** [comment]
Do you know which kind of encryption is used for the certificate? Could you try adding the following dependency in your POM file:
```xml
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcpkix-jdk15on</artifactId>
</dependency>
```

**Comment by bentito** [comment]
Okay, I was able to get free and reproduce it. It does reproduce and sadly that dep add doesn't fix it. 

I am setup to try things easier now if there are other ideas...

**Comment by laxmikantbpandhare** [comment]
> Do you know which kind of encryption is used for the certificate? Could you try adding the following dependency in your POM file:
> 
> ```
> <dependency>
>   <groupId>org.bouncycastle</groupId>
>   <artifactId>bcpkix-jdk15on</artifactId>
> </dependency>
> ```

Sure @metacosm - I will also try this scenario.

**Comment by laxmikantbpandhare** [comment]
> > ```
> <dependency>
>   <groupId>org.bouncycastle</groupId>
>   <artifactId>bcpkix-jdk15on</artifactId>
> </dependency>
> ```

@metacosm - I modified the `pom.xml` file and added above dependency but still, it failed with below error.


```
laxmikantbhaskarpandhare@lpandhar-mac resources % kubectl logs memcached-quarkus-operator-operator-59c65bdf84-lm47l
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-03-08 07:42:43,836 INFO  [io.jav.ope.Operator] (main) Registered Controller: 'memcachedcontroller' for CRD: 'class com.example.Memcached' for namespace(s): [all namespaces]
2022-03-08 07:42:43,841 INFO  [io.qua.ope.run.AppEventListener] (main) Quarkus Java Operator SDK extension 2.0.0.Beta5 (commit: f520a8c on branch: f520a8c49b2b91405a12b3e5b465780c8962b918)
2022-03-08 07:42:43,851 INFO  [io.jav.ope.Operator] (main) Operator SDK 1.9.6 (commit: 8a9c614) built on Thu Sep 02 19:07:29 GMT 2021 starting...
2022-03-08 07:42:43,852 INFO  [io.jav.ope.Operator] (main) Client version: 5.7.2
2022-03-08 07:42:44,010 ERROR [io.jav.ope.Operator] (main) Error retrieving the server version: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchVersion(OpenShiftClusterOperationsImpl.java:50)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.getVersion(DefaultOpenShiftClient.java:568)
	at io.javaoperatorsdk.operator.Operator.start(Operator.java:77)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener.onStartup(AppEventListener.java:31)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(AppEventListener_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.zig:147)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:307)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:289)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:601)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.handleVersionGet(ClusterOperationsImpl.java:62)
	at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchOpenshift4Version(OpenShiftClusterOperationsImpl.java:56)
	at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchVersion(OpenShiftClusterOperationsImpl.java:48)
	... 24 more
```

**Comment by metacosm** [comment]
Try updating your dependencies as well, you're using really old versions…

**Comment by jmrodri** [comment]
Closing as this has not come up in a long time.
